config/routes.rb
Rails.application.routes.draw do
  resources :registers

  root 'registers#index'

end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "Hello world!"
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:email, :name, :notify)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/layouts/_footer.html.erb
<hr>
Copyrite: unknown@me.com. All rights reserved.

app/views/layouts/_header.html.erb
<img src="/assets/AWS-5bb01d1e652d3a7c574d6c953d9f4ace.png" alt="AWS logo" height="80" width="200" />
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyWebApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<%=yield %>
<%= render "layouts/footer" %>

</body>
</html>

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notify %><br>
    <%= f.check_box :notify %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Hello mate! The next BIG thing is coming soon... Register your interest!</h2>

<table border=1 padding=5>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Notify Me</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.email %></td>
        <td><%= register.name %></td>
        <td><%= register.notify %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registration', new_register_path %>

app/views/registers/new.html.erb
<h1>New Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @register.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @register.name %>
</p>

<p>
  <strong>Notify:</strong>
  <%= @register.notify %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>